<?php

/**
 * Brand palettes for runtime theming.
 *
 * - `colors`: 5 swatches for the admin Appearance picker
 * - `tokens`: full CSS/Tailwind token map applied site-wide
 *
 * Semantic note (Artisanal Warmth):
 * - token `primary` = espresso structure (#3D1A0E)
 * - token `accent` / `secondary` = hearth CTA orange
 * - admin swatch `primary` = CTA orange, `accent` = espresso (matches UI mock)
 */

$status = [
    'success' => '#2E7D32',
    'error' => '#C62828',
    'warning' => '#EF9F27',
    'info' => '#185FA5',
    'on-error' => '#ffffff',
    'error-container' => '#ffdad6',
    'on-error-container' => '#93000a',
];

$artisanalWarmthTokens = array_merge($status, [
    'primary' => '#3D1A0E',
    'accent' => '#E8572A',
    'surface' => '#FDF6EE',
    'card' => '#FFFFFF',
    'text-primary' => '#1A1A1A',
    'text-muted' => '#6B6B6B',
    'border-base' => '#E5DDD4',
    'surface-dim' => '#dcd9d9',
    'surface-bright' => '#fcf9f8',
    'surface-container-lowest' => '#ffffff',
    'surface-container-low' => '#f6f3f2',
    'surface-container' => '#f0eded',
    'surface-container-high' => '#eae7e7',
    'surface-container-highest' => '#e5e2e1',
    'on-surface' => '#1c1b1b',
    'on-surface-variant' => '#514440',
    'inverse-surface' => '#313030',
    'inverse-on-surface' => '#f3f0ef',
    'outline' => '#84746f',
    'outline-variant' => '#d6c2bd',
    'surface-tint' => '#825343',
    'on-primary' => '#ffffff',
    'primary-container' => '#3d1a0e',
    'on-primary-container' => '#b47e6d',
    'inverse-primary' => '#f6b8a5',
    'secondary' => '#b02f00',
    'on-secondary' => '#ffffff',
    'secondary-container' => '#fc6537',
    'on-secondary-container' => '#5c1400',
    'tertiary' => '#110f0a',
    'on-tertiary' => '#ffffff',
    'tertiary-container' => '#26241f',
    'on-tertiary-container' => '#8f8b84',
    'primary-fixed' => '#ffdbd0',
    'primary-fixed-dim' => '#f6b8a5',
    'on-primary-fixed' => '#321207',
    'on-primary-fixed-variant' => '#663c2d',
    'secondary-fixed' => '#ffdbd1',
    'secondary-fixed-dim' => '#ffb59f',
    'on-secondary-fixed' => '#3b0a00',
    'on-secondary-fixed-variant' => '#862200',
    'tertiary-fixed' => '#e8e1da',
    'tertiary-fixed-dim' => '#ccc6be',
    'on-tertiary-fixed' => '#1e1b17',
    'on-tertiary-fixed-variant' => '#4a4641',
    'background' => '#fcf9f8',
    'on-background' => '#1c1b1b',
    'surface-variant' => '#e5e2e1',
]);

return [
    'default_palette' => 'artisanal_warmth',

    'default_font_heading' => 'Playfair Display',

    'default_font_body' => 'Inter',

    'palettes' => [
        [
            'id' => 'artisanal_warmth',
            'label' => 'Artisanal Warmth',
            'colors' => [
                'primary' => '#E8572A',
                'accent' => '#3D1A0E',
                'page_bg' => '#FDF6EE',
                'cards' => '#FFFFFF',
                'text' => '#1A1A1A',
            ],
            'tokens' => $artisanalWarmthTokens,
        ],
        [
            'id' => 'cocoa_espresso',
            'label' => 'Cocoa Espresso',
            'colors' => [
                'primary' => '#A0522D',
                'accent' => '#2C1810',
                'page_bg' => '#F5EDE4',
                'cards' => '#FFFFFF',
                'text' => '#1C1410',
            ],
            'tokens' => array_merge($status, [
                'primary' => '#2C1810',
                'accent' => '#A0522D',
                'surface' => '#F5EDE4',
                'card' => '#FFFFFF',
                'text-primary' => '#1C1410',
                'text-muted' => '#6B5A4E',
                'border-base' => '#E0D2C4',
                'surface-dim' => '#d4cbc3',
                'surface-bright' => '#f5ede4',
                'surface-container-lowest' => '#ffffff',
                'surface-container-low' => '#f0e6db',
                'surface-container' => '#ebe0d4',
                'surface-container-high' => '#e5d8ca',
                'surface-container-highest' => '#e0d2c4',
                'on-surface' => '#1c1410',
                'on-surface-variant' => '#56463c',
                'inverse-surface' => '#342820',
                'inverse-on-surface' => '#f3ebe3',
                'outline' => '#7a6a5e',
                'outline-variant' => '#d0c0b2',
                'surface-tint' => '#6b4423',
                'on-primary' => '#ffffff',
                'primary-container' => '#2c1810',
                'on-primary-container' => '#c4a484',
                'inverse-primary' => '#e0b896',
                'secondary' => '#8B4513',
                'on-secondary' => '#ffffff',
                'secondary-container' => '#c47840',
                'on-secondary-container' => '#3a1c08',
                'tertiary' => '#1a120c',
                'on-tertiary' => '#ffffff',
                'tertiary-container' => '#2a2018',
                'on-tertiary-container' => '#9a8c80',
                'primary-fixed' => '#f0dcc8',
                'primary-fixed-dim' => '#e0b896',
                'on-primary-fixed' => '#2c1810',
                'on-primary-fixed-variant' => '#5c3d28',
                'secondary-fixed' => '#f5d9c0',
                'secondary-fixed-dim' => '#e0b080',
                'on-secondary-fixed' => '#2a1408',
                'on-secondary-fixed-variant' => '#6b3410',
                'tertiary-fixed' => '#e8dfd6',
                'tertiary-fixed-dim' => '#ccc2b8',
                'on-tertiary-fixed' => '#1a120c',
                'on-tertiary-fixed-variant' => '#4a4038',
                'background' => '#f5ede4',
                'on-background' => '#1c1410',
                'surface-variant' => '#e0d2c4',
            ]),
        ],
        [
            'id' => 'honey_cream',
            'label' => 'Honey Cream',
            'colors' => [
                'primary' => '#D4A017',
                'accent' => '#5C3D1E',
                'page_bg' => '#FFF8E7',
                'cards' => '#FFFFFF',
                'text' => '#2A2118',
            ],
            'tokens' => array_merge($status, [
                'primary' => '#5C3D1E',
                'accent' => '#D4A017',
                'surface' => '#FFF8E7',
                'card' => '#FFFFFF',
                'text-primary' => '#2A2118',
                'text-muted' => '#7A6B52',
                'border-base' => '#EDE0C4',
                'surface-dim' => '#e8dfc8',
                'surface-bright' => '#fff8e7',
                'surface-container-lowest' => '#ffffff',
                'surface-container-low' => '#faf3e0',
                'surface-container' => '#f5edd6',
                'surface-container-high' => '#f0e6cc',
                'surface-container-highest' => '#ede0c4',
                'on-surface' => '#2a2118',
                'on-surface-variant' => '#5c4e3a',
                'inverse-surface' => '#3a3024',
                'inverse-on-surface' => '#f7f0e0',
                'outline' => '#8a7a60',
                'outline-variant' => '#ddd0b0',
                'surface-tint' => '#8a6a28',
                'on-primary' => '#ffffff',
                'primary-container' => '#5c3d1e',
                'on-primary-container' => '#d4b896',
                'inverse-primary' => '#e8c878',
                'secondary' => '#B8860B',
                'on-secondary' => '#ffffff',
                'secondary-container' => '#e8c040',
                'on-secondary-container' => '#4a3808',
                'tertiary' => '#1f180e',
                'on-tertiary' => '#ffffff',
                'tertiary-container' => '#2e2618',
                'on-tertiary-container' => '#9a8e78',
                'primary-fixed' => '#f5e6c8',
                'primary-fixed-dim' => '#e8c878',
                'on-primary-fixed' => '#3a2810',
                'on-primary-fixed-variant' => '#6b4a20',
                'secondary-fixed' => '#f8e8b0',
                'secondary-fixed-dim' => '#e8c860',
                'on-secondary-fixed' => '#3a2c08',
                'on-secondary-fixed-variant' => '#7a5c10',
                'tertiary-fixed' => '#ebe4d6',
                'tertiary-fixed-dim' => '#d0c8b8',
                'on-tertiary-fixed' => '#1f180e',
                'on-tertiary-fixed-variant' => '#4a4030',
                'background' => '#fff8e7',
                'on-background' => '#2a2118',
                'surface-variant' => '#ede0c4',
            ]),
        ],
        [
            'id' => 'berry_bakery',
            'label' => 'Berry Bakery',
            'colors' => [
                'primary' => '#A12B5B',
                'accent' => '#3D1A2E',
                'page_bg' => '#FBF5F7',
                'cards' => '#FFFFFF',
                'text' => '#1F1418',
            ],
            'tokens' => array_merge($status, [
                'primary' => '#3D1A2E',
                'accent' => '#A12B5B',
                'surface' => '#FBF5F7',
                'card' => '#FFFFFF',
                'text-primary' => '#1F1418',
                'text-muted' => '#6B5A62',
                'border-base' => '#E8D8DE',
                'surface-dim' => '#e0d4d8',
                'surface-bright' => '#fbf5f7',
                'surface-container-lowest' => '#ffffff',
                'surface-container-low' => '#f6eef1',
                'surface-container' => '#f0e6ea',
                'surface-container-high' => '#eadde2',
                'surface-container-highest' => '#e8d8de',
                'on-surface' => '#1f1418',
                'on-surface-variant' => '#564048',
                'inverse-surface' => '#342428',
                'inverse-on-surface' => '#f5ecef',
                'outline' => '#7a6670',
                'outline-variant' => '#d8c4cc',
                'surface-tint' => '#825060',
                'on-primary' => '#ffffff',
                'primary-container' => '#3d1a2e',
                'on-primary-container' => '#c898a8',
                'inverse-primary' => '#e8a0b8',
                'secondary' => '#8B1E4A',
                'on-secondary' => '#ffffff',
                'secondary-container' => '#c45078',
                'on-secondary-container' => '#4a1028',
                'tertiary' => '#180e14',
                'on-tertiary' => '#ffffff',
                'tertiary-container' => '#281820',
                'on-tertiary-container' => '#9a8890',
                'primary-fixed' => '#f5d8e4',
                'primary-fixed-dim' => '#e8a0b8',
                'on-primary-fixed' => '#2a1020',
                'on-primary-fixed-variant' => '#5c2840',
                'secondary-fixed' => '#f5c8d8',
                'secondary-fixed-dim' => '#e890b0',
                'on-secondary-fixed' => '#2a0818',
                'on-secondary-fixed-variant' => '#6b1838',
                'tertiary-fixed' => '#e8dde2',
                'tertiary-fixed-dim' => '#ccc0c6',
                'on-tertiary-fixed' => '#180e14',
                'on-tertiary-fixed-variant' => '#4a3840',
                'background' => '#fbf5f7',
                'on-background' => '#1f1418',
                'surface-variant' => '#e8d8de',
            ]),
        ],
        [
            'id' => 'sage_loaf',
            'label' => 'Sage Loaf',
            'colors' => [
                'primary' => '#6B8F71',
                'accent' => '#2F3E32',
                'page_bg' => '#F4F7F2',
                'cards' => '#FFFFFF',
                'text' => '#1A211C',
            ],
            'tokens' => array_merge($status, [
                'primary' => '#2F3E32',
                'accent' => '#6B8F71',
                'surface' => '#F4F7F2',
                'card' => '#FFFFFF',
                'text-primary' => '#1A211C',
                'text-muted' => '#5A6B5E',
                'border-base' => '#D5DDD4',
                'surface-dim' => '#d0d8ce',
                'surface-bright' => '#f4f7f2',
                'surface-container-lowest' => '#ffffff',
                'surface-container-low' => '#eef2eb',
                'surface-container' => '#e6ece3',
                'surface-container-high' => '#dee6da',
                'surface-container-highest' => '#d5ddd4',
                'on-surface' => '#1a211c',
                'on-surface-variant' => '#445048',
                'inverse-surface' => '#2a322c',
                'inverse-on-surface' => '#eef2eb',
                'outline' => '#6a786e',
                'outline-variant' => '#c4d0c4',
                'surface-tint' => '#5a7a60',
                'on-primary' => '#ffffff',
                'primary-container' => '#2f3e32',
                'on-primary-container' => '#a8c0ae',
                'inverse-primary' => '#b0d0b8',
                'secondary' => '#4A7A52',
                'on-secondary' => '#ffffff',
                'secondary-container' => '#80b088',
                'on-secondary-container' => '#1e3a24',
                'tertiary' => '#121814',
                'on-tertiary' => '#ffffff',
                'tertiary-container' => '#222a24',
                'on-tertiary-container' => '#889488',
                'primary-fixed' => '#d8e8dc',
                'primary-fixed-dim' => '#b0d0b8',
                'on-primary-fixed' => '#1a281e',
                'on-primary-fixed-variant' => '#3a5040',
                'secondary-fixed' => '#d0e8d4',
                'secondary-fixed-dim' => '#a0c8a8',
                'on-secondary-fixed' => '#142818',
                'on-secondary-fixed-variant' => '#345838',
                'tertiary-fixed' => '#dde4de',
                'tertiary-fixed-dim' => '#c0c8c0',
                'on-tertiary-fixed' => '#121814',
                'on-tertiary-fixed-variant' => '#3a443c',
                'background' => '#f4f7f2',
                'on-background' => '#1a211c',
                'surface-variant' => '#d5ddd4',
            ]),
        ],
        [
            'id' => 'midnight_bakery',
            'label' => 'Midnight Bakery',
            'colors' => [
                'primary' => '#C45C26',
                'accent' => '#121212',
                'page_bg' => '#F7F3EF',
                'cards' => '#FFFFFF',
                'text' => '#141414',
            ],
            'tokens' => array_merge($status, [
                'primary' => '#121212',
                'accent' => '#C45C26',
                'surface' => '#F7F3EF',
                'card' => '#FFFFFF',
                'text-primary' => '#141414',
                'text-muted' => '#666666',
                'border-base' => '#E0DAD4',
                'surface-dim' => '#d8d2cc',
                'surface-bright' => '#f7f3ef',
                'surface-container-lowest' => '#ffffff',
                'surface-container-low' => '#f0ebe6',
                'surface-container' => '#e8e2dc',
                'surface-container-high' => '#e0dad4',
                'surface-container-highest' => '#d8d2cc',
                'on-surface' => '#141414',
                'on-surface-variant' => '#4a4540',
                'inverse-surface' => '#2a2a2a',
                'inverse-on-surface' => '#f0ece8',
                'outline' => '#787270',
                'outline-variant' => '#ccc4bc',
                'surface-tint' => '#6a5040',
                'on-primary' => '#ffffff',
                'primary-container' => '#121212',
                'on-primary-container' => '#b0a8a0',
                'inverse-primary' => '#d0c8c0',
                'secondary' => '#A04820',
                'on-secondary' => '#ffffff',
                'secondary-container' => '#e07840',
                'on-secondary-container' => '#4a2008',
                'tertiary' => '#0a0a0a',
                'on-tertiary' => '#ffffff',
                'tertiary-container' => '#1e1e1e',
                'on-tertiary-container' => '#888888',
                'primary-fixed' => '#e8e0d8',
                'primary-fixed-dim' => '#d0c8c0',
                'on-primary-fixed' => '#121212',
                'on-primary-fixed-variant' => '#404040',
                'secondary-fixed' => '#f5d8c8',
                'secondary-fixed-dim' => '#e0a080',
                'on-secondary-fixed' => '#2a1008',
                'on-secondary-fixed-variant' => '#6b3018',
                'tertiary-fixed' => '#e0e0e0',
                'tertiary-fixed-dim' => '#c0c0c0',
                'on-tertiary-fixed' => '#0a0a0a',
                'on-tertiary-fixed-variant' => '#404040',
                'background' => '#f7f3ef',
                'on-background' => '#141414',
                'surface-variant' => '#e0dad4',
            ]),
        ],
    ],

    'fonts' => [
        'heading' => [
            'Playfair Display',
            'Lora',
            'Merriweather',
            'Cormorant Garamond',
            'Libre Baskerville',
            'DM Serif Display',
            'Roboto',
        ],
        'body' => [
            'Inter',
            'Source Sans 3',
            'Nunito Sans',
            'IBM Plex Sans',
            'Work Sans',
            'DM Sans',
            'Roboto',
        ],
    ],
];
